### PR TITLE
Add dotenv-linter (Closes #155)

### LINKED ISSUE #155: [Installer] Add dotenv-linter
# Add dotenv-linter

We want to add `dotenv-linter` because it's a nice cross-platform tool to check that a `.env` file is what it should be.

This could be as simple as copying `_example`, updating the github releases
info, and doing a find and replace on a few file system path names.

Also: We'll want to get this added to <https://dotenv-linter.github.io/#/installation>:

Mac, Linux:

```bash
curl -sS https://webinstall.dev/dotenv-linter | bash
```

Windows 10:

```pwsh
curl.exe -A MS https://webinstall.dev/dotenv-linter | pwsh
```

# How to create a webi installer

[Video Tutorial: How to create a webi Installer](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the example template and update with info from Official Releases:
   <https://github.com/dotenv-linter/dotenv-linter/releases>
   ```bash
   rsync -av _example/ dotenv-linter/
   ```
   - [ ] update `dotenv-linter/release.js` to use the official repo
   - [ ] Learn how `dotenv-linter` unpacks (i.e. as a single file? as a .tar.gz? as
         a .tar.gz with a folder named dotenv-linter)
   - [ ] find and replace to change the name
     - [ ] update `dotenv-linter/install.sh` (see `bat` and `jq` as examples)
     - [ ] update `dotenv-linter/install.ps1` (see `bat` and `jq` as examples)
3. Needs an updated tagline and cheat sheet
   - [ ] update `dotenv-linter/README.md`
     - [ ] official URL
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

It's also okay to have multiple people work on part of this (i.e. the Cheat
Sheet can be done independently from the `install.sh`)

### PR DESCRIPTION
**Pull request by patrick-gu**
For the README, I just copied the [dotenv-linter usage guide](https://dotenv-linter.github.io/#/usage) as it was fairly short.

Please let me know if I missed anything!

### CODE REVIEW

**Comment by coolaj86** [comment]
I'll merge this after I update the Cheat Sheet.

The purpose of the Cheat Sheet is to be original content that highlights the simplest and most useful use cases. We don't use direct copies of the author's content.

**Comment by coolaj86** [comment]
Tested working on Mac and Linux

```bash
curl -sS https://beta.webinstall.dev/dotenv-linter | bash
```

**Comment by coolaj86** [comment]
Failed to install on Windows 10.

```bash
curl.exe -A MS https://beta.webinstall.dev/dotenv-linter | bash
```

I suspect that this has the same issue as <https://beta.webinstall.dev/bat> and probably needs the same notification.

**Comment by patrick-gu** [comment]
I believe installing on Windows should work now. I just copied some of the code from bat/install.ps1 and it seems to work, moving the one executable.
Thank you!

**Comment by coolaj86** [comment]
@patrick-gu Actually, the way that you had it before was more correct.

What needs to be updated is the README.md to give the instructions to install the Windows Redistributable. That's what's missing.

**Comment by patrick-gu** [comment]
I copied the instructions from bat into the README. Please let me know which use cases/examples I should put in the cheat sheet.

**Comment by coolaj86** [comment]
@patrick-gu Sorry for falling behind on this. I made the changes to the Cheat Sheet, squashed, and I'm approving now.

**Review by coolaj86 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
