### PR TITLE
chore: style updates #325

### PR DESCRIPTION
**Pull request by y0rune**

### CODE REVIEW

**Comment by coolaj86** [comment]
Thanks. I'll try to work on webi again later this week and review this. :)

**Comment by y0rune** [comment]
Okay I rebased it ;)

**Comment by y0rune** [comment]
Ohh and I use that script https://github.com/y0rune/webi-installers/commit/146bf94864359ef73f74f125b62ff8aae3b59eb0

**Review by coolaj86 — APPROVED** [review]
I also fixed some whitespace, added some tests, and cleaned up the ssh-* stuff to match the proposed style.

**Pull request merged**
