### PR TITLE
Add gh installer

### PR DESCRIPTION
**Pull request by onwuvic**
* [x] update CHANGE-ME/release.js to use the official repo
 * [x] find and replace to change the name
 * [x] update CHANGE-ME/install.sh (see bat and jq as examples)
 * [x] update CHANGE-ME/install.ps1 (see bat and jq as examples)

### CODE REVIEW

**Comment by coolaj86** [comment]
Hey @onwuvic, I'm reviewing this right now.

It looks like you did edit the `README.md` to include a real cheat sheet. Could you do that?

**Comment by coolaj86** [comment]
@onwuvic It looks like the path is wrong on Windows:

```txt
Move-Item : Cannot find path 'C:\Users\coola\.local\tmp\gh\bin\gh.exe' because it does not exist.
At C:\Users\coola\.local\tmp\gh.install.ps1:95 char:9
+         Move-Item -Path ".\$pkg_cmd_name\bin\gh.exe" -Destination "$p ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\coola\.local\tmp\gh\bin\gh.exe:String) [Move-Item], Ite
   mNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
```

Would you check the `gh` o`zip` and adjust the windows installer path accordingly? (it may not be in `bin/` as mac and linux are, for example)

**Comment by onwuvic** [comment]
@coolaj86 I will check it out

**Comment by onwuvic** [comment]
@coolaj86 finally figured it out. Using this `".\$pkg_cmd_name\bin\gh.exe"` instead of `".\bin\gh.exe"`. Check and see if it is working at intended

**Comment by coolaj86** [comment]
@onwuvic All that's left on this is the cheat sheet. I've verified that it's working. Do you want to finish that up?

**Comment by onwuvic** [comment]
@coolaj86 I don’t really understand how to write the cheat sheet or what exactly to write.

**Review by coolaj86 — APPROVED** [review]

**Comment by coolaj86** [comment]
Thanks @onwuvic  and @khairnarsaurabh23, this is now live at https://webinstall.dev/gh, and featured on the homepage (https://webinstall.dev).

**Pull request merged**
