### PR TITLE
atomicparsley: README.md corrections

### PR DESCRIPTION
**Pull request by howyallare**
- artwork image manipulation is macOS-only
- ffmpeg 4.0+ can add artwork to mp4 files

### CODE REVIEW

**Comment by coolaj86** [comment]
@howyallare Do you know how to add mp4 atoms (not ID3 tags) for album art with `ffmpeg`? Can you link to some documentation or show examples?

I was trying and trying and everything I found on StackOverflow or from GPT failed, which is why I turned to AtomicParsley.

**Review by coolaj86 — APPROVED** [review]

**Comment by howyallare** [comment]
ffmpeg -i input.mp4 -i input.jpg -map 0 -map 1 -c copy -disposition:v:1 attached_pic output.mp4

**Comment by coolaj86** [comment]
@howyallare: I thought I had tried that one before. I tried it again just now:

```sh
ffmpeg -i test-audiobook.m4b -i test-square.png -map 0 -map 1 -c copy -disposition:v:1 attached_pic test-audiobook.with-cover.m4b
```

```text
Input #1, png_pipe, from 'test-square.png':
  Duration: N/A, bitrate: N/A
  Stream #1:0: Video: png, rgba(pc), 40x38 [SAR 5669:5669 DAR 20:19], 25 fps, 25 tbr, 25 tbn
[ipod @ 0x15be06110] Tag text incompatible with output codec id '98314' ([0][0][0][0])
Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
Error initializing output stream 0:3 --
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
  Stream #1:0 -> #0:3 (copy)
    Last message repeated 1 times
```

I'm on ffmpeg v5:

```text
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.30)
  configuration: --prefix=/Volumes/tempdisk/sw --extra-cflags=-fno-stack-check --arch=arm64 --cc=/usr/bin/clang --enable-gpl --enable-libopenjpeg --enable-libopus --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libwebp --enable-libass --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libsnappy --enable-libaom --enable-libvidstab --enable-libzimg --enable-libsvtav1 --enable-version3 --pkg-config-flags=--static --disable-ffplay --enable-postproc --enable-nonfree --enable-neon --enable-runtime-cpudetect --disable-indev=qtkit --disable-indev=x11grab_xcb
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
```

**Comment by howyallare** [comment]
It looks like I spoke too soon. It doesn't appear to work the same for audio files. You can get past that error by adding `-f mp4` before the output file (to force use of mp4/mov codec), bit it does't add the artwork. For normal audio files (.m4a), that appears to add artwork only if there is pre-existing artwork. AP does better in that case, but it doesn't appear to read audiobook files (.m4b) at all.

**Comment by coolaj86** [comment]
`.m4b` and `.m4a` are supposedly the exact same file type, just a different extension to signal "Open this with Music.app" as opposed to "Open this with Books.app".

Many podcasts are distributed as `.m4a`, but if you rename them to `.m4b` you get a better default experience - bookmarks, etc.

**Comment by howyallare** [comment]
All true, but I have to first remux the random .m4b files I rustled up in order for AP to add artwork.  If that isn't true for you, I don't know where the difference lies.  For me, AP doesn't like the original file brand in the container even though it seems OK. Something for me to look into.

It's probably best to reverse my edit re: ffmpeg and artwork. It's not a complete solution, it seems. I had only ever used it on video files, and I guess I assumed any MP4 would work.

**Pull request merged**
