### PR TITLE
fix shellcheck warnings

### PR DESCRIPTION
**Pull request by y0rune**
Re: #395

### CODE REVIEW

**Comment by y0rune** [comment]
All right I will do it ;) Sorry I added it into a issue, but it is a good idea to do it here ;)

**Comment by coolaj86** [comment]
This looks good, but since it is so broad, I just need a little more time to review it.

One note: I prefer `grep` over the bash-isms because `grep` is more well-known.

I'd prefer to silence warnings about using `grep` or `sed` rather than switch to bash-isms.

**Comment by y0rune** [comment]
All right! In next commits I will use grep! 
Thank you reviewing and sharing the goods way!

**Comment by coolaj86** [comment]
Thanks for this. Sorry it's been getting stale.

1. Could you make the commits more atomic?
  - removing all of the `echo`s is one commit
2. We don't need exports, and we don't want bash-isms
3. Change `/bin/bash` to `/bin/sh` and remove `function` as its own commit

**Comment by coolaj86** [comment]
Closing for now, waiting for new PR.

**Pull request closed without merging**
