### PR TITLE
feat+fix: explicit libc detection for musl, gnu, libc/none/static

### PR DESCRIPTION
**Pull request by coolaj86**
re #728 

This change ended up being larger in scope than I thought.

It's definitely more of a "manually test" than "just look at the code".

### macOS, Linux, Alpine

```sh
mv ~/.local/ ~/.local.1.old/

# This should fail gracefully on Alpine
curl -sS https://next.webinstall.dev/cmake | sh

# All of these should work
curl -sS https://next.webinstall.dev/node | sh
curl -sS https://next.webinstall.dev/atomicparsley | sh
curl -sS https://next.webinstall.dev/bat | sh
curl -sS https://next.webinstall.dev/jq | sh
curl -sS https://next.webinstall.dev/yq | sh
curl -sS https://next.webinstall.dev/ffmpeg | sh

source ~/.config/envman/PATH.env

node --version
AtomicParsley --version
bat -V
jq -V
yq -V
ffmpeg -version
```

```sh
mv ~/.local/ ~/.local.2.old/

curl -sS https://next.webinstall.dev/ | sh
export WEBI_HOST='https://next.webinstall.dev'

webi cmake
webi node atomicparsley bat jq yq ffmpeg
```

### Windows

```pwsh
curl.exe -A MS https://next.webinstall.dev/cmake | powershell
curl.exe -A MS https://next.webinstall.dev/node | powershell
curl.exe -A MS https://next.webinstall.dev/atomicparsley | powershell
curl.exe -A MS https://next.webinstall.dev/bat | powershell
curl.exe -A MS https://next.webinstall.dev/jq | powershell
curl.exe -A MS https://next.webinstall.dev/yq | powershell
curl.exe -A MS https://next.webinstall.dev/ffmpeg | powershell
```

## Test Matrix

- All should correctly detect libc version
- All except ❌s are expected to install
- Everything that installs should be able to run `xxxx --version` or `xxxx --help`

✅ - should work without special considerations
🐧 - GNU build (Linux, and maybe Windows)
💪 - Musl build (must work on Alpine, may work on GNU)
🪟 - MSVC build
❌ - expected to fail early
⚡️ - no libc

|                            | Linux        | Alpine           | macOS | Windows |
| --------------- | ---------- | ------------ | ------- | --------- |
| cmake                |  🐧             |  ❌                 | ✅         | ✅             |
| node                  |   🐧             |  💪                 | ✅         | ✅             |
| AtomicParsley   |   🐧             |  💪                 | ✅         | ✅             |
| bat                     |   💪             |  💪                 | ✅         | 🪟             |
| jq                       |   ⚡️             |  ⚡️                 | ✅         | ✅             |
| yq                       |   ⚡️             |  ⚡️                 | ✅         | ✅             |
| ffmpeg               |   ⚡️             |  ⚡️                 | ✅         | ✅             |

### CODE REVIEW

**Comment by coolaj86** [comment]
## AJ Has Tested

- [x] Apline
- [ ] Linux
- [ ] macOS
- [ ] Windows

**Comment by HacDan** [comment]
Getting 502'd on the gateway. Domain resolves to `166.70.154.115`

**Comment by HacDan** [comment]
## HacDan Has Tested

This fails on Windows 10 (x86-64) doesn't seem to be architecture related, though 
```powershell
curl.exe -A MS https://next.webinstall.dev/cmake | powershell
```

Returns this error:
```powershell
Copy-Item : Could not find a part of the path 'C:\Users\Admin\.local\opt\cmake\bin\cmake.exe'.
At C:\Users\Admin\.local\tmp\cmake.install.ps1:174 char:1
+ Copy-Item -Path "$pkg_src" -Destination "$pkg_dst" -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand
```


### These all install without issue on Windows 10 (x86-64) 
```powershell
curl.exe -A MS https://next.webinstall.dev/node | powershell
curl.exe -A MS https://next.webinstall.dev/atomicparsley | powershell
curl.exe -A MS https://next.webinstall.dev/bat | powershell
curl.exe -A MS https://next.webinstall.dev/jq | powershell
curl.exe -A MS https://next.webinstall.dev/yq | powershell
curl.exe -A MS https://next.webinstall.dev/ffmpeg | powershell
```

**Comment by coolaj86** [comment]
@HacDan cmake installer itself was bad on Windows. That's fixed.

I've got all passing results. Interestingly, `bat` now installs the `gnu` version because the libc changes caused the prioritization to favor Windows static / `gnu` builds over `msvc` builds - which is great.

Are you ready to greenlight this?

**Review by HacDan — APPROVED** [review]
LGTM!

**Pull request merged**
