### PR TITLE
doc(bat) add Files section

### PR DESCRIPTION
**Pull request by HacDan**
Add files section for `bat` to README.md

### CODE REVIEW

**Comment by coolaj86** [comment]
Also needs `~/.config/bat/config`, if you don't mind.

**Comment by HacDan** [comment]
I was referencing the `install.sh` script when writing up the Files section but I may have missed the creation of the file.

**Comment by coolaj86** [comment]
It doesn't actually create it yet, but it's one of those files that you'd want to see at-a-glance to know that it exists at all.

It _should_ create it and the fact that it doesn't doesn't make it less valuable to know about it.
You pickin' up what I'm putting down?

**Comment by HacDan** [comment]
I'm smelling what you're steppin' in, don't you worry. 

I pushed a Fixup commit. Should be all set. If you'd rather I squash them, I suppose I can do that.

**Review by coolaj86 — APPROVED** [review]
Approved. Rebased and squashed

**Pull request merged**
