### PR TITLE
vim-commentary installer

### PR DESCRIPTION
**Pull request by ryanburnette**
I am working on an installer for [vim-commentary](https://github.com/tpope/vim-commentary).

Should it be in vim-essentials? I think so.

# Preview Cheat Sheet

https://github.com/ryanburnette/webi-installers/tree/vim-commentary/vim-commentary

### CODE REVIEW

**Comment by ryanburnette** [comment]
#386

**Comment by ryanburnette** [comment]
wip, still need to test

**Comment by coolaj86** [comment]
I just tried this out vim-commentary for the first time.

It's simple and works perfectly.

It's a crying shame I've been living below my privileges all these years.

**Comment by ryanburnette** [comment]
It's also a crying shame that I have never finished this installed, but I asked if you'd do it because I know it'll take you a lot less time than me. Shameful but true.

**Review by coolaj86 — APPROVED** [review]
Fixed up for the new Posix scripting style. Also updated vim-sensible to match.

**Pull request merged**
