### PR TITLE
feat: Adding terramate support to webi

### PR DESCRIPTION
**Pull request by Ga13Ou**
There's no easy way to install a specific version of terramate other than installing the latest through brew or downloading a specific release. So I thought why not add it this useful installer 😉

### CODE REVIEW

**Comment by coolaj86** [comment]
This is up for testing on https://beta.webinstall.dev/terramate

The installer seems to work, however, the README doesn't have any real valuable information in it.

Can you come up with a Cheat Sheet with the most valuable snippets for daily driver use?

Some examples:
- https://webinstall.dev/node/
- https://webinstall.dev/k9s/
- https://webinstall.dev/aliasman/
- https://webinstall.dev/hugo/

It doesn't need to be extravagant, but it should be something that allows someone that's confused by the main repo's README or big documentation site to get started in a few seconds or minutes. Does that make sense?

**Comment by Ga13Ou** [comment]
Thank you for the feedback and suggestions! 🙌

I've made the requested changes and added a Cheat Sheet to the README

**Comment by coolaj86** [comment]
The cheat sheet looks great. I'll make a few tweaks later tonight and I think we'll have this live tomorrow.

**Review by coolaj86 — APPROVED** [review]
Bringing it in!

**Comment by Ga13Ou** [comment]
Sorry to ping you directly @coolaj86, but is there any recent change that may have broken that feature? it used to work a week ago but now when I ran `curl -sS https://webi.sh/terramate@v0.11.2 | sh`

I get the following error:
````

 curl -sS https://webi.sh/terramate@v0.11.2 | sh


>>> Welcome to Webi! - modern tools, instant installs.  <<<
    We expect your experience to be absolutely perfect!

    Success? Star it!   https://github.com/webinstall/webi-installers
    Problem? Report it: https://github.com/webinstall/webi-installers/issues
                        (your system is Darwin/arm64 with libc & curl+wget)

Bootstrapping Webi
    Found ~/.local/bin/webi
    Running ~/.local/bin/webi terramate@0.11.2

Installing terramate ...
    Found  ~/.local/bin

    Error: no 'terramate@0.11.2' release for 'darwin' (libc) on 'aarch64' as one of 'tar,exe,zip,xz,git,dmg,pkg'

        Latest Stable: undefined
        CPUs:
        OSes:
        libcs:
        Package Formats:
        (check that the package name and version are correct)

      Double check at https://webi.sh/api/releases/terramate@0.11.2.tab
          ?os=darwin&arch=aarch64&libc=libc&formats=tar,exe,zip,xz,git,dmg,pkg&pretty=true
````

Note that: I am requesting terramate@**v**0.11.2 and in the logs I see terramate@0.11.2
  is that normal?

**Pull request merged**
