### PR TITLE
feat: add sttr

### PR DESCRIPTION
**Pull request by abhimanyu003**
sttr is a cross-platform, cli app to perform various operations on string.

 - [x] `sttr` for unixes
 - [x] `sttr` for osx ( darwin )
 - [x] `sttr` for Windows
 - [x] Cheat sheet
 
 Github repo: https://github.com/abhimanyu003/sttr

### CODE REVIEW

**Comment by coolaj86** [comment]
I've been wanting something like this, actually.

Looks good.

I'll give it a test drive and probably update the cheat sheet with some things I find particularly useful.

**Comment by coolaj86** [comment]
Notes for things I want to test:

- Which base32 do you use? Crockford Base32? or something else?
- Does it accept a `salt` for the hashing functions?

**Comment by abhimanyu003** [comment]
Hello @coolaj86, 
Thanks so much for you comments.
* base32, base64, and  others are specified by RFC 4648 https://rfc-editor.org/rfc/rfc4648.html
* At this point we don't support salt for md5,sha etc. But this is something that can be added with additional flags.  But for algos like `bcrypt` you can set custom number of rounds like `sttr bcrypt -h`

**Review by coolaj86 — APPROVED** [review]
Tested working on Mac and Linux at least.

I love the vim-keybinding support. Nice touch.

I do want to give this my own cheat sheet treatment, but I'll get this pushed through first.

**Comment by coolaj86** [comment]
Live at https://webinstall.dev/sttr

**Pull request merged**
