### PR TITLE
feat: add barebones ollama start

### PR DESCRIPTION
**Pull request by todpunk**
The basics, untested because I don't know how

### CODE REVIEW

**Comment by todpunk** [comment]
It works (I can verify that I previously had 0.1.3 and now have 0.1.5 with Webi)
```
webi-installers git:(add-ollama) sh install-ollama.sh 

Thanks for using webi to install 'ollama' on 'Linux/x86_64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/webi-installers/issues

Lovin' it? Say thanks with a Star on GitHub:
        https://github.com/webinstall/webi-installers

WARN: possible PATH conflict between 'ollama v0.1.5' and currently installed version
    /home/todhansmann/.local/bin/ollama (new)
    /home/todhansmann/bin/ollama (existing)
Downloading ollama from
https://github.com/jmorganca/ollama/releases/download/v0.1.5/ollama-linux-amd64

Saved as /home/todhansmann/Downloads/webi/ollama/0.1.5/ollama-linux-amd64
Moving /home/todhansmann/Downloads/webi/ollama/0.1.5/ollama-linux-amd64
Installing to /home/todhansmann/.local/opt/ollama-v0.1.5/bin/ollama
Installed 'ollama v0.1.5' as /home/todhansmann/.local/bin/ollama

```

**Comment by coolaj86** [comment]
I have some notes started here:
https://github.com/webinstall/webi-installer-requests/issues/72

**Comment by coolaj86** [comment]
And don't forget to lint:

- [ ]
   ```sh
   git pull --rebase upstream main
   npm run fmt
   npm run lint
   ```

**Comment by todpunk** [comment]
I got the readme to the point in v1.0 that I had any experience with (I just run it, I don't care about webui exposures and stuff). I didn't just copy/paste env vars because I have little idea what they do and not much particular interest in spending time learning them at the moment, so that seems fraught with peril for other readers for me to do.

**Comment by coolaj86** [comment]
Adding a nice preview.. 
Screenshot 2023-10-28 at 4 15 37 PM

**Review by coolaj86 — APPROVED** [review]
For some weird reason my internal sorting was choosing v0.0.x over v0.1.x, so I'll have to look into that later, but I put in a workaround for now by just filtering out v0.0.x.

I also expanded the cheat sheet.

Thanks for this!

**Comment by coolaj86** [comment]
P.S. If you don't use this with a web ui... how do you use it? Or plan to use it?

I'd love to train it on my code and then get editor integration.

**Comment by todpunk** [comment]
I just use it on the CLI. `ollama run mistral` and interact with it there. If I get to the point that I'm running it on a server or something, it will be in kubernetes and just through the ollama exposed API, but I don't want a web UI at all for it. If anything like that is to be done, I'll just build my own using that API.

**Pull request merged**
