### PR TITLE
giving webi installer the gift of crabz

### PR DESCRIPTION
**Pull request by copyleftdev**
adding a rust tool called crabz

### CODE REVIEW

**Comment by coolaj86** [comment]
This can be previewed at https://beta.webinstall.dev/crabz

**Comment by copyleftdev** [comment]
@coolaj86 getting a 500 response from the beta url

`curl 'https://beta.webinstall.dev/crabz' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cache-Control: max-age=0' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: _gid=GA1.2.295070613.1697438704; _ga=GA1.2.1699432686.1697323350; _ga_34RD616HZZ=GS1.1.1697589563.5.1.1697589637.0.0.0' \
  -H 'Referer: https://github.com/webinstall/webi-installers/pull/664' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed`

**Comment by coolaj86** [comment]
It's because the FrontMatter is malformed:


```yaml
---

### Title: Crabz
Homepage: [Crabz on GitHub](https://github.com/sstadick/crabz)
Tagline: |
  Crabz: A cross-platform, fast, compression and decompression tool written in Rust.

---
```

**Comment by coolaj86** [comment]
I corrected it ad-hoc:

```yaml
---
Title: Crabz
Homepage: [Crabz on GitHub](https://github.com/sstadick/crabz)
Tagline: |
  Crabz: A cross-platform, fast, compression and decompression tool written in Rust.
---
```

Now the page renders:
https://beta.webinstall.dev/crabz

**Review by coolaj86 — APPROVED** [review]
Fixed the installers and reworked the README.

This will go live momentarily... 🙂

**Pull request merged**
