### PR TITLE
feat: use `git` as source for releases

### PR DESCRIPTION
**Pull request by coolaj86**
# Preview

- https://next.webinstall.dev/vim-commentary
- https://next.webinstall.dev/api/releases/vim-commentary.json?pretty=true

Also:

```sh
# update webi
curl https://webi.sh/ | sh

# view vim-commentary info on 'next'
export WEBI_HOST='https://next.webinstall.dev'
webi --info vim-commentary
```

```sh
# install via 'next'
curl https://next.webinstall.dev/vim-commentary | sh
```

# Details

There are a number of types of utilities that only need a git tag:

- VimScript (`vim-ale`)
- POSIX Shell Scripts (`aliasman`, `duckdns.sh`)
- PowerShell

This allows us to use `git` as a source of release info.

```sh
node ./_common/git.js
```

```json5
{
  name: 'ale-v3.3.0',
  version: 'v3.3.0',
  date: '2022-12-25T20:30:21.000Z',
  ext: 'git',
  command: 'git clone --depth=1 --single-branch --branch v3.3.0 https://github.com/dense-analysis/ale.git'
}
```

Re: https://github.com/webinstall/webi-roadmap/issues/17

### CODE REVIEW

**Review by y0rune — CHANGES_REQUESTED** [review]
Hello!
I think the `.sh` script should be added in the different branch.
As far I saw you parsed it not adding something new. 

--
Marcin

**Comment by coolaj86** [comment]
> I think the `.sh` script should be added in the different branch.
> As far I saw you parsed it not adding something new.

@y0rune Which one are you talking about?

All of the changes here are to support git releases. The change to the `vim-commentary` installer is part of testing that this works.

**Comment by y0rune** [comment]
Now I got only the 11 files before was 40 :D So I will check it now ;)

**Review by y0rune — APPROVED** [review]
LGTM!

**Comment by coolaj86** [comment]
Thanks for the thorough review!

**Pull request merged**
