### PR TITLE
Added shfmt

### PR DESCRIPTION
**Pull request by adithyasunil26**
Created installer for shfmt as mentioned in #105.

### CODE REVIEW

**Comment by coolaj86** [comment]
Looking now.

**Review by coolaj86 — APPROVED** [review]
This is good enough to get started, so I'll merge it in, but there are a few other things I'd like if you're willing to do them. I'll list those in a minute.

**Comment by coolaj86** [comment]
- [ ] Reduce the cheat sheet to the most important things.

It looks like you've listed out the full `shfmt --help`. Could you give any examples? What's options do you find most useful?

**Comment by coolaj86** [comment]
- [ ] Update README.md of `shfmt`

Could you also make a PR on `shfmt` adding the Webi install instructions? That often looks like this:

## Common Example

~~~md
## macOS

Homebrew:

```bash
brew install xxxxx
```

Webi:

```bash
curl -sS https://webinstall.dev/xxxxx | bash
```

## Linux

Apt:

```bash
sudo apt -y install xxxxx
```

Webi:

```bash
curl -sS https://webinstall.dev/xxxxx | bash
```

## Windows

Choco:

```bash
choco install xxxxx
```

Webi:

```bash
curl.exe -A MS https://webinstall.dev/xxxxx | powershell
```
~~~

## Specific Example

It doesn't look like `shfmt` has other installers, so in this case it may be appropriate to suggest something like this:

~~~md
## Install

`shfmt` by downloading from GitHub Releases (<https://github.com/mvdan/sh/releases>) and placing the binary in your `PATH`.

You can use **Webi** to do this for you:

**Mac, Linux**:

```bash
curl -sS https://webinstall.dev/xxxxx | bash
```

**Windows 10**:

```bash
curl.exe -A MS https://webinstall.dev/xxxxx | powershell
```
~~~

**Comment by adithyasunil26** [comment]
Sure. I will work on these changes and open PRs soon.

**Pull request merged**
