### PR TITLE
Add dotenv+caddy+serviceman example to caddy cheatsheet

### PR DESCRIPTION
**Pull request by ryanburnette**
This adds an example to the caddy cheatsheet that demonstrates using dotenv, caddy, and serviceman to create a caddy service that loads env vars with dotenv.

### CODE REVIEW

**Comment by coolaj86** [comment]
@ryanburnette You can use `--envfile` in caddy... but it doesn't handle quotes correctly in earlier versions:
- https://github.com/caddyserver/caddy/issues/4686

**Comment by coolaj86** [comment]
Agreed. Do it!

**Comment by ryanburnette** [comment]
I will. Standby for an updated PR.

**Comment by coolaj86** [comment]
This is Red Leader, standing by.

**Comment by coolaj86** [comment]
I have mention of this in #649

**Pull request closed without merging**
