### PR TITLE
Added lf

### PR DESCRIPTION
**Pull request by adithyasunil26**
Solves #149

### CODE REVIEW

**Comment by coolaj86** [comment]
FYI: I plan to review both of your PRs and merge them in on Saturday. I haven't forgotten.

**Comment by adithyasunil26** [comment]
Okay take your time 👍

**Comment by coolaj86** [comment]
Sorry, I was sick over the weekend.

**Review by coolaj86 — APPROVED** [review]
did some cleanup and fixes on this

**Pull request merged**
