### PR TITLE
Add zoxide installer

### PR DESCRIPTION
**Pull request by ajeetdsouza**
Hey, I just discovered webi and I love how easy it is to use!

I've created an installer for [zoxide](https://github.com/ajeetdsouza/zoxide), a cross-shell autojump tool written in Rust.

### CODE REVIEW

**Comment by coolaj86** [comment]
Hello! sorry for the long wait. If I don't have this in (or feedback given) by end of day Tuesday, please bug me about it.

**Comment by ajeetdsouza** [comment]
Thank you! Before you merge this - is there a way to install manpages using webi?

**Comment by coolaj86** [comment]
Yes. I don't recall exactly, but I think you plop them into `~/.local/var/share/man/<programname>` - or something very similar to that.

**Comment by ajeetdsouza** [comment]
@coolaj86 I've updated the scripts for the latest release and I've tested it on Windows and Linux. Could you take a look at it?

>  I think you plop them into ...

Afaik, `~/.local/share/man` would not work on macOS. Since there is no reliably cross-platform way to do this without root, I'm going to leave that out for now.

**Comment by ajeetdsouza** [comment]
Hey @coolaj86, were you able to look into this?

**Comment by ajeetdsouza** [comment]
Hey @coolaj86, a gentle reminder - are you back from your vacation yet?

**Comment by iamc** [comment]
> @coolaj86 I've updated the scripts for the latest release and I've tested it on Windows and Linux. Could you take a look at it?
> 
> > I think you plop them into ...
> 
> Afaik, `~/.local/share/man` would not work on macOS. Since there is no reliably cross-platform way to do this without root, I'm going to leave that out for now.

I have also been looking at setting up the man pages (as well as bash etc completions) and it seems man looks for manpages, for every `path` in `$PATH`, in `path/../man`.

I just checked and at least in my linux it does.

**Comment by ajeetdsouza** [comment]
@iamc I would love to support manpages, but we'd need to verify if this works on macOS first.

**Comment by iamc** [comment]
@ajeetdsouza I have no access to macOS right now, but I may have in a few days. If so, I'll report back.

**Comment by ajeetdsouza** [comment]
Sounds great. Thanks.

**Comment by coolaj86** [comment]
I am back from vacation. I'll slate this for this evening.

**Comment by iamc** [comment]
No time yet for taking a look at the macOS support for manpages. My plan is to test it in a VirtualBox environment as I see that there are macOS [Vagrant boxes available]( https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=macos). Hopefully later this week.

**Comment by ajeetdsouza** [comment]
No worries @iamc. Do ping me here if you find anything, we can add manpages in a future PR.

**Comment by iamc** [comment]
OK, I'll definitely take look at it as I want to add manpages and also bash-completion also to other packages I use often.

**Comment by ajeetdsouza** [comment]
Hey @coolaj86, were you able to take a look at this PR?

**Comment by ajeetdsouza** [comment]
Hey @coolaj86, just a reminder about this PR.

**Comment by coolaj86** [comment]
I'm live streaming, doing this, right now. It _will_ finally get done. _Finally_. My apologies! :)

**Comment by ajeetdsouza** [comment]
Hey @coolaj86, watching your live stream right now! You might want to use the [GitHub CLI](https://cli.github.com/), you can simply `gh pr checkout 223` instead of using a script :smile:

**Review by coolaj86 — APPROVED** [review]

**Comment by ajeetdsouza** [comment]
@coolaj86 responding to the livestream: you have to `cd` into a directory the "hard way" at least once before you can "jump" to it.

**Comment by ajeetdsouza** [comment]
Once you `z ~/Projects`, you can use `z proj` no matter where on your filesystem you are.

**Comment by coolaj86** [comment]
I think it would be good to have a follow-up PR that does all of the shell config automatically.

Here's a good example:
https://github.com/webinstall/webi-installers/blob/main/pyenv/install.sh

**Comment by ajeetdsouza** [comment]
Fair point, but `zoxide init` comes with options (see `zoxide init --help`). Also, a user might want it installed on `zsh`, but they also have `bash` installed on their system.

Since it's just a one-liner to copy-paste, I've tried to leave this upto the user, as such.

**Comment by coolaj86** [comment]
Then I'd say at least add a `pkg_done_message` with something like


```bash
You'll need to set up your shell manually.
See https://webinstall.dev/zoxide
```

Example: https://github.com/webinstall/webi-installers/blob/main/golang/install.sh#L100

**Comment by ajeetdsouza** [comment]
@coolaj86 that's pretty neat. Is there a way to do this with PowerShell too?

**Comment by coolaj86** [comment]
The powershell scripts are less sophisticated. You could just output the instructions at the end of the script.

**Review by Alejandrotx89 — APPROVED** [review]

**Pull request merged**
