### PR TITLE
vim-airline installer

### PR DESCRIPTION
**Pull request by ryanburnette**
- [x] vim-airline installer
- [x] vim-airline-themes installer

### CODE REVIEW

**Comment by ryanburnette** [comment]
I know the cheatsheet is sparse, but vim-airline is a plugin that modifies the interface and I personally use defaults. The screenshot is all that I need in the cheat sheet.

**Comment by ryanburnette** [comment]
The `airline.vim` config file is actually empty if you just install vim-airline from webi, but I like to create it in case the user wants to use it, and later if you install vim-airline-themes it'll add a line to that file.

**Comment by ryanburnette** [comment]
@coolaj86 Do you mind taking a look at the themes installer with me? My intent here is to:

- place the airline.vim file if it is not present
- if it is present, look to see if a theme is set, if one is set, leave it alone, if one isn't set, append the theme setting line from the theme installer airline.vim file

I believe I have it working but it might be good for me to add some echoes.

Unless you have some edits regarding that, this is ready to merge.

**Comment by ryanburnette** [comment]
I know you'll also want more elaborate cheat sheets, but I use this basically with defaults. You install it and get the new behavior. I don't have much else to add.

**Review by coolaj86 — APPROVED** [review]
Muchas garcias!

(I just made a few style and format edits)

**Pull request merged**
