### PR TITLE
Refactor to make sure printf format strings don't use variables and make sure variables are inside quotes.

### PR DESCRIPTION
**Pull request by rishavnandi**
Updated printf strings from variable interpolation to variables substitution, according to the schellcheck suggestions and formatted the code using shfmt.

### CODE REVIEW

**Comment by coolaj86** [comment]
Re:
- #502
- #503

**Review by coolaj86 — APPROVED** [review]
I added a fix that shellcheck couldn't catch because it's embedded in a heredoc. I also added a different fix for the embedded script.

**Comment by coolaj86** [comment]
@rishavnandi Thanks!

Drop your Đash Wallet address here (or DM me) and I'll send a tip / buy you lunch.

:)

**Comment by rishavnandi** [comment]
> @rishavnandi Thanks!
> 
> Drop your Đash Wallet address here (or DM me) and I'll send a tip / buy you lunch.
> 
> :)

Hi!, Thanks for approving the changes and making them better!

Here's my dash wallet address (thank you so much!) -> XejUdFnFesXRvHwdFXeWTTWiH3niqGtpBP

**Comment by coolaj86** [comment]
Sent!

**Pull request merged**
