### PR TITLE
Fixed all shellcheck warnings and style updates #500

### PR DESCRIPTION
**Pull request by ShyamMahajan**
Removed wrapping around if blocks

### CODE REVIEW

**Comment by coolaj86** [comment]
@ShyamMahajan When you look at the output from `shellcheck` you should see that it gives different change suggestions for the different if blocks.

For example, ifs with `-z` need to be changed to `!`:

```diff
- if [ -z "$(command -v git)" ]; then
+ if ! command -v git; then
```

And only the if blocks that `shellcheck` complains about need to be adjusted. The others can be left alone.

Will you update the PR please?

**Comment by ShyamMahajan** [comment]
@coolaj86 updated the PR. please review. Thanks!

**Review by coolaj86 — APPROVED** [review]
@ShyamMahajan Thanks!

Drop your Đash Wallet address here (or DM me) and I'll send a tip / buy you lunch.

:)

**Comment by coolaj86** [comment]
@ShyamMahajan Here's another one that's pretty easy:
https://github.com/webinstall/webi-installers/issues/474

**Pull request merged**
