### PR TITLE
Mega: POSIX Shell Updates

### PR DESCRIPTION
**Pull request by TarekArar99**

### CODE REVIEW

**Comment by coolaj86** [comment]
`pushd` enters a directory and `popd` leaves that directory.

The correct way to replace `pushd` and `popd` with `cd` and a subshell `()` would be like this:

```sh
pushd ...
    # do some stuff
    # do more stuff
popd ...
```

```sh
(
    cd ... || exit
    # do some stuff
    # do more stuff
)
```

However, if there's any place where variables are being changed within the subshell that needs to be looked at more closely.

**Comment by y0rune** [comment]
As far I see it should be linked into https://github.com/webinstall/webi-installers/issues/480. When somebody goes to that issue can see if somebody is currently working on that issue ;)

**Comment by coolaj86** [comment]
@TarekArar99 Are you able to make those changes?

**Review by coolaj86 — APPROVED** [review]

**Comment by coolaj86** [comment]
@TarekArar99 Because I needed to include this in a broader update, I finished it up myself.

Would you like to continue with #474 or one of these?
https://github.com/webinstall/webi-installers/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by TarekArar99** [comment]
I will check it tomorrow if I have some time.

**Pull request merged**
