### PR TITLE
Added pyenv 

### PR DESCRIPTION
**Pull request by adithyasunil26**
Solves issue #180

### CODE REVIEW

**Comment by coolaj86** [comment]
Oh wow, I was just putting this as a note-to-self and you already got to it. Thanks.

I love the cheat sheet you put together.

Do you think you could add the Windows PowerShell pyenv to this as well?
https://github.com/pyenv-win/pyenv-win

I think this also needs `.pyenv/shims` added to the path.

FYI: `webi` comes with `pathman` which figures out the `zsh` vs `bash` vs `fish` vs `PowerShell` issues:

```bash
pathman add ~/.pyenv/shim
```

That's how webi adds itself to shells.

I'll try to test this out and get it merged it tomorrow.

**Comment by adithyasunil26** [comment]
> Oh wow, I was just putting this as a note-to-self and you already got to it. Thanks.

Haha I did not realise that was a note you were writing to yourself. It was detailed enough to be an issue.

> I love the cheat sheet you put together.

Glad you liked it.
 
> Do you think you could add the Windows PowerShell pyenv to this as well?
> https://github.com/pyenv-win/pyenv-win

I do not use windows and hence I don't really know PowerShell syntax very well and I can't test what I'm writing. It will be better if someone who knows it well enough and can test it makes the script.
 
> I think this also needs `.pyenv/shims` added to the path.
> FYI: `webi` comes with `pathman` which figures out the `zsh` vs `bash` vs `fish` vs `PowerShell` issues:

Okay, thank you for letting me know. I was not aware of `pathman`'s functionalities.  I will commit these changes now.

**Comment by coolaj86** [comment]
Sorry for the long wait, I had slated it for the weekend but then forgot.

I'm doing some python work today, so I'll try to review and get this in.

**Comment by coolaj86** [comment]
I've updated, rebased, and tested.

I've got it up at https://beta.webinstall.dev/pyenv for further testing and will likely complete the merge tonight.

**Review by coolaj86 — APPROVED** [review]

**Pull request merged**
