### PR TITLE
adding creedasaurus/gprox

### PR DESCRIPTION
**Pull request by creedasaurus**
Hoping to leverage webi to install a simple local ssl proxy I wrote. Nothing too wild. I do need to double check with someone on Windows that the Powershell script works ok. Haven't done that just yet.

### CODE REVIEW

**Comment by coolaj86** [comment]
I've got this up for test at https://beta.webinstall.dev/gprox

```bash
curl -sS https://beta.webinstall.dev/gprox | bash
```

Could you put a little more info about what gprox is and what it's useful for? Why is `gprox` awesome?

Warning: I did a force push rebasing the current master, so you might want to `git reset --hard HEAD~10; git pull`.

**Comment by creedasaurus** [comment]
Definitely! I was super tired when I wrote this so it definitely could use some more. I also tend to blank out when it comes to a good readme! 😓

**Comment by creedasaurus** [comment]
Hmmm. Buddy of mine said the install from powershell didn't work. 

```powershell
& : The term 'C:\Users\stevi.local\bin\webi.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:3
+ & "$Env:USERPROFILE.local\bin\webi.ps1" "gprox"
+   ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\stevi.local\bin\webi.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by coolaj86** [comment]
`'C:\Users\stevi.local\bin\webi.ps1'`

Should be `'C:\Users\stevi\.local\bin\webi.ps1'`.

Is there a special character in his username? `stevi` doesn't seem like a normal complete name.

**Comment by coolaj86** [comment]
> I also tend to blank out when it comes to a good readme!

Here are some questions to answer to get the juices flowing:

What exactly does gprox do?

Who would want to use it? How to _you_ use it? Why did you build it? What are some alternavites?

**Comment by creedasaurus** [comment]
Updated the cheat sheet (both on this and the repo for the tool itself)

**Comment by coolaj86** [comment]
I forgot to review this the other day. It looks good. Merged.

**Pull request merged**
