### PR TITLE
feat(terraform): add Terraform package

### LINKED ISSUE #432: Add terraform
Terraform is the defacto cloud provisioner. So if its possible to enable terraform, that'll be a huge boost
Link: https://www.terraform.io/downloads

### PR DESCRIPTION
**Pull request by J-Curragh**
Closes webinstall/webi-installer-requests#36.

Added Terraform as a package. It requests all releases from https://releases.hashicorp.com/terraform/index.json

Passed the test in `_webi/test.js`. 

I can confirm it is working on both of my systems (macos/arm64 and windows/amd64), see below for output.

macos/arm64:
```
sh install-terraform.sh

Thanks for using webi to install 'terraform' on 'Darwin/arm64'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/webi-installers/issues

Lovin' it? Say thanks with a Star on GitHub:
        https://github.com/webinstall/webi-installers

Downloading terraform from
https://releases.hashicorp.com/terraform/1.3.2/terraform_1.3.2_darwin_arm64.zip

Saved as /Users/jcli/Downloads/webi/terraform/1.3.2/terraform_1.3.2_darwin_arm64.zip
Extracting /Users/jcli/Downloads/webi/terraform/1.3.2/terraform_1.3.2_darwin_arm64.zip
Installing to /Users/jcli/.local/opt/terraform-v1.3.2/bin/terraform
Installed 'terraform v1.3.2' as /Users/jcli/.local/bin/terraform
```

windows/amd64:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; powershell.exe .\install-terraform.ps1
PATH not changed.

Downloading terraform from https://releases.hashicorp.com/terraform/1.3.2/terraform_1.3.2_windows_amd64.zip to C:\Users\jakec\Downloads\webi\terraform_1.3.2_windows_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.7M  100 11.7M    0     0  3284k      0  0:00:03  0:00:03 --:--:-- 3285k
Installing terraform
Unpacking C:\Users\jakec\Downloads\webi\terraform_1.3.2_windows_amd64.zip
Install Location: C:\Users\jakec.local\opt\terraform-v1.3.2\bin\terraform.exe
Copying into 'C:\Users\jakec.local\bin\terraform.exe' from 'C:\Users\jakec.local\opt\terraform-v1.3.2\bin\terraform.exe'

C:\ terraform -v
Terraform v1.3.2
```

### CODE REVIEW

**Comment by J-Curragh** [comment]
Hi, @coolaj86 @ryanburnette, would you mind reviewing this when you get a chance? Thanks

**Review by ryanburnette — COMMENTED** [review]
Looks good to me. Any feedback from @coolaj86?

**Comment by y0rune** [comment]
LGTM too! Thank you @J-Curragh ;) What do you think @coolaj86?

**Review by coolaj86 — APPROVED** [review]
@J-Curragh My apologies for letting this go so long. You did everything right and I can tell you put above-average effort into this.

I think I just got distracted and confused on the day I looked at this and never got back to it. 😞

The consolation prize is that it makes it in today. 🎉

And as a standard offer to all contributors: If you drop or DM me your Đash Wallet address here I'll be more than happy to send a tip / buy you lunch.

Again, many apologies and many thanks.

**Comment by J-Curragh** [comment]
> @J-Curragh My apologies for letting this go so long. You did everything right and I can tell you put above-average effort into this.
> 
> I think I just got distracted and confused on the day I looked at this and never got back to it. 😞
> 
> The consolation prize is that it makes it in today. 🎉
> 
> And as a standard offer to all contributors: If you drop or DM me your Đash Wallet address here I'll be more than happy to send a tip / buy you lunch.
> 
> Again, many apologies and many thanks.

Hey, thanks for getting this merged in, it's my first FOSS contribution ✨
I just appreciate the opportunity ❤️ cool project!

**Pull request merged**
