### PR TITLE
[Installer] - otsgo

### PR DESCRIPTION
**Pull request by emdneto**
otsgo is a simple CLI and API client for One-Time Secret written in Go.

Project: https://github.com/emdneto/otsgo

### CODE REVIEW

**Comment by coolaj86** [comment]
Hey, just wanted to let you know that I appreciate this and I'll be taking a look at it within the next week or so.

I just spent a bunch of time on Webi PRs and updates a few weeks ago and I've needed to focus on some other projects for a bit to get caught up on them.

:)

**Comment by coolaj86** [comment]
Sorry for the late reply. I've got this up on beta:

https://beta.webinstall.dev/otsgo

There are just a few style issues I'd like to have fixed before we push this to prod:

- The name of this package should be `ots`, not `otsgo` (because the binary is called `ots`)
- All code blocks should have language tags, such as `` ```bash ``
- Delete example comments, such as `/** Note: Delete this Comment!                                               **/`
- All cheat sheet commands should be copy/pastable - no leading `$`
- Output should be in its own block. Example:
   ```bash
    mycommand subcommand --flag
   ```
   ```txt
   example output goes here
   > wow! pretty colors
   > looks good
   ... waiting
   Done!
   ```
- run `npm run prettier` before committing

**Comment by coolaj86** [comment]
This is a really cool tool. I could see myself using this.

I'd love to get it up this week. :)

**Comment by emdneto** [comment]
Hi @coolaj86 ,
Sorry for the delay, but I want to tell you that:
I fixed the package name and also changed the directory name;
I removed the example comments;
I fixed the README.md cheatsheet code blocks with ```bash and removed the leading $

**Review by coolaj86 — APPROVED** [review]
Thank you!

(sorry for the month-long delay but... you know how it goes 🙃)

**Pull request merged**
