### PR TITLE
feat(cmake): Added CMake package

### PR DESCRIPTION
**Pull request by brthngnsh**
Addon changes:
- Added share directory to install script to fix CMAKE_ROOT not found issue.
- Added a simple CPP Hello World program for CMake usage.

Caution:
- Need to test Powershell script.

### CODE REVIEW

**Comment by brthngnsh** [comment]
this commit resolves #579

**Comment by coolaj86** [comment]
For what I can see this looks good. Just as I started reviewing it my starting cutting in and out. I'll check again tomorrow when I can test on Windows too.

**Comment by coolaj86** [comment]
On beta for now:
https://beta.webinstall.dev/cmake

**Comment by coolaj86** [comment]
I just checked it out on Windows and it works there too. Pulling in now.

**Review by coolaj86 — APPROVED** [review]
@brthngnsh Thanks!

I made some updates to formatting and switched this to the package style rather than the single-exe style.

Drop your Đash Wallet address here (or DM me) and I'll send a tip / buy you lunch.

:)

**Pull request merged**
