### PR TITLE
Added kubectx installer

### PR DESCRIPTION
**Pull request by michaelpaesold**
See https://github.com/ahmetb/kubectx

Implements issue #173

Collaborative work of Nico Kerschbaumer and me

### CODE REVIEW

**Comment by coolaj86** [comment]
I'm looking at this now.

**Review by coolaj86 — COMMENTED** [review]
Looks good enough to add and get started, though I would like some more info, which I'll mention in a moment.

**Review by coolaj86 — APPROVED** [review]

**Comment by coolaj86** [comment]
Should this also install `kubens`?

Also, I've made a PR to kubectx to set the version: https://github.com/ahmetb/kubectx/pull/279 Re: https://github.com/ahmetb/kubectx/issues/125

**Comment by coolaj86** [comment]
It would be nice to have a little more info in the Cheat Sheet. I'm not a k8s user, but what's there isn't quite enough for me to get a handle on why I'd use this if I were.

I'd recommend adding some info about why it's personally important to use, or a few quick commands for things that you do on a daily (or otherwise regular) basis.

**Comment by michaelpaesold** [comment]
> Should this also install `kubens`?

Actually yes, should this be a separate installation or is there precedence for bundling the two tools?

**Comment by coolaj86** [comment]
In this case it probably should be a separate installer because it's published as a separate binary:

https://github.com/ahmetb/kubectx/releases/tag/v0.9.1

Otherwise, if it were in the same tarball, I'd give an example of modifying the installer to move both around.

I'd recommend modifying the `releases.js` of both to make sure that `kubectx` is filtered from `kubens` and vice-versa, that might look like this: https://github.com/webinstall/webi-installers/blob/master/caddy/releases.js

```js
    // remove kubens, etc from kubectx list
    all.releases = all.releases.filter(function (rel) {
      return !/kubectx/i.test(rel.name);
    });
```

**Comment by coolaj86** [comment]
Also, would you make a PR to the README or install docs page of `kubectx` to add as well?

For many projects updating the install section might look something like this:

~~~md
## macOS

Homebrew:

```bash
brew install xxxxx
```

Webi:

```bash
curl -sS https://webinstall.dev/xxxxx | bash
```

## Linux

Apt:

```bash
sudo apt -y install xxxxx
```

Webi:

```bash
curl -sS https://webinstall.dev/xxxxx | bash
```

## Windows

Choco:

```bash
choco install xxxxx
```

Webi:

```bash
curl.exe -A MS https://webinstall.dev/xxxxx | powershell
```
~~~

**Comment by nikersch** [comment]
> In this case it probably should be a separate installer because it's published as a separate binary:
> 
> https://github.com/ahmetb/kubectx/releases/tag/v0.9.1
> 
> (otherwise, if it were in the same tarball, I'd give an example of modifying the installer to move both around)
> 
> I'd recommend modifying the `releases.js` of both to make sure that `kubectx` is filtered from `kubens` and vice-versa. That might look like this: https://github.com/webinstall/webi-installers/blob/master/caddy/releases.js
> 
> ```js
>     // remove kubens, etc from kubectx list
>     all.releases = all.releases.filter(function (rel) {
>       return !/kubectx/i.test(rel.name);
>     });
> ```

I can submit a PR for separate kubens installer.

**Pull request merged**
