### PR TITLE
add:'gh' cheatsheet

### PR DESCRIPTION
**Pull request by khairnarsaurabh23**
I've added cheat cheet for 'gh' command-line. Cheat sheet describes the utility of 'gh' command-line.

### CODE REVIEW

**Comment by coolaj86** [comment]
The cheat sheet is still empty in this commit. All that's changed is the description.

Do you use `gh`?

**Comment by khairnarsaurabh23** [comment]
Not often.  But I'll fix the issue very soon. 
@coolaj86

**Comment by khairnarsaurabh23** [comment]
Yes ,  definitely I'll do that

**Comment by khairnarsaurabh23** [comment]
@coolaj86  I've formatted  and previewed the code. The code matches the styles of other cheat sheets.

**Pull request merged**
