### PR TITLE
[wip] setcap-netbind and vps-essentials

### PR DESCRIPTION
**Pull request by ryanburnette**
- [x] setcap-netbind
- [ ] recreate vps-utils as vps-essentials leaving vps-utils garbage intact
- [ ] follow meta installer pattern from vps-essentials

### CODE REVIEW

**Comment by ryanburnette** [comment]
@coolaj86 It looks like the purpose of vps-utils is to bundle multiple installers into one, but I think that's not worth doing. There's a better way if we want to have a bundle of installers that won't involve duplication. I'm seeing myip and vps-myip that look like they do the same thing.

If someone wants vps-utils maybe they should just run this command:

```bash
webi myip setcap-netbind addswap
```

Or we could have a way to set up a bundle by having a README.md with front matter listing the packages and the documentation just links to the included installers.

**Comment by ryanburnette** [comment]
It looks like vim-essentials is a good example of a meta installer. I can make vps-utils match that pattern.

**Comment by ryanburnette** [comment]
Will rename to vps-essentials.

**Review by coolaj86 — APPROVED** [review]
I'm taking your WIP for `setcap-netbind` and rolling with it. We can do the full `vps-essentials` meta package later.

**Pull request merged**
